version: '3.8'

services:
  nginx:
    image: nginx:1.19.10
    container_name: nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - mysql

  php:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab11docker
      MYSQL_USER: lab11
      MYSQL_PASSWORD: lab11
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6001:80"
    networks:
      - backend
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  frontend:
  backend:
